### ISSUE TITLE
Can we use with our op-geth?

### ISSUE THREAD

**Issue by uok825** [AlexBHarley/op-stack-hyperlane#1]
Basically, this is the question.  How can I use this modded opstack with my op-geth?

**Comment by AlexBHarley** [comment]
This mod requires you to be running your own standalone L2, ie, deploying the L1 contracts, then running op-geth, op-node, op-batcher and op-proposer.

The changes this mod makes are to the op-node. So you won't be able to run op-geth on an existing network and benefit from the changes here.
